import type { Metadata } from "next";
import "./globals.css";
import { TeamsProvider } from "@/context/TeamsProvider";

export const metadata: Metadata = {
  title: "Car Streams",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body suppressHydrationWarning className={` antialiased`}>
        <TeamsProvider>{children}</TeamsProvider>
      </body>
    </html>
  );
}
