import { Team } from "@/types";

export const teams: Team[] = [
  {
    id: 1,
    name: "Global",
    spelling: "global",
    flag: "https://flagcdn.com/w320/un.png",
    car: "/cars/4.global.webp",
  },
  {
    id: 2,
    name: "Spain",
    spelling: "🇪🇸",
    flag: "https://flagcdn.com/es.svg",
    car: "/cars/3.españa.webp",
  },
  {
    id: 3,
    name: "Jhope Indonesia",
    spelling: " 🇮🇩",
    flag: "https://flagcdn.com/id.svg",
    car: "/cars/5.indonesia.webp",
  },
  {
    id: 4,
    name: "Egypt",
    spelling: " 🇪🇬",
    flag: "https://flagcdn.com/eg.svg",
    car: "/cars/6.egypt.webp",
  },
  {
    id: 5,
    name: "Brazil",
    spelling: " 🇧🇷",
    flag: "https://flagcdn.com/br.svg",
    car: "/cars/7.brazil.webp",
  },
  {
    id: 6,
    name: "Japan",
    spelling: " 🇯🇵",
    flag: "https://flagcdn.com/jp.svg",
    car: "/cars/8.japan.webp",
  },
  {
    id: 7,
    name: "Panama",
    spelling: " 🇵🇦",
    flag: "https://flagcdn.com/pa.svg",
    car: "/cars/9.panama.webp",
  },
  // {
  //   id: 8,
  //   name: "India",
  //   spelling: " 🇮🇳",
  //   flag: "https://flagcdn.com/in.svg",
  //   car: "cars/5.indonesia.webp",
  // },
  {
    id: 9,
    name: "Thailand",
    spelling: " 🇹🇭",
    flag: "https://flagcdn.com/th.svg",
    car: "/cars/11.thailand.webp",
  },
  {
    id: 10,
    name: "Vietnam",
    spelling: " 🇻🇳",
    flag: "https://flagcdn.com/vn.svg",
    car: "/cars/10.vietnam.webp",
  },
  {
    id: 11,
    name: "Peru",
    spelling: " 🇵🇪",
    flag: "https://flagcdn.com/pe.svg",
    car: "/cars/12.peru.webp",
  },
  {
    id: 12,
    name: "Turkey",
    spelling: " 🇹🇷",
    flag: "https://flagcdn.com/tr.svg",
    car: "/cars/13.turkye.webp",
  },
];
